package com.payu.global.wallet.service.discovery.client;

import com.netflix.client.config.IClientConfig;
import com.netflix.loadbalancer.AbstractServerList;
import com.netflix.loadbalancer.Server;
import com.netflix.loadbalancer.ServerList;
import org.springframework.cloud.consul.client.CatalogClient;
import org.springframework.cloud.consul.discovery.ConsulServer;
import org.springframework.cloud.consul.discovery.ConsulServerList;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.ArrayList;
import java.util.List;

/**
 * Auguments the Spring context generated by Consul auto configuration, to inject a correct  ServerList<Server> instance.
 * Created by nicu on 19.02.2015.
 */
@Configuration
public class ConsulContext {
    @Bean
    public ServerList<Server> ribbonServerList(final CatalogClient catalogClient) {
        return adapter(new ConsulServerList(catalogClient, DiscoverServices.CLIENT_NAME));
    }

    private ServerList<Server> adapter(final ConsulServerList consulServerList) {
        return new AbstractServerList<Server>() {
            @Override
            public void initWithNiwsConfig(IClientConfig clientConfig) {
                consulServerList.initWithNiwsConfig(clientConfig);
            }

            @Override
            public List<Server> getInitialListOfServers() {
                return adapt(consulServerList.getInitialListOfServers());
            }

            @Override
            public List<Server> getUpdatedListOfServers() {
                return adapt(consulServerList.getUpdatedListOfServers());
            }

            private List<Server> adapt(List<ConsulServer> initialListOfServers) {
                ArrayList<Server> list = new ArrayList<Server>();
                for (ConsulServer consulServer : initialListOfServers) {
                    list.add(consulServer);
                }
                return list;
            }
        };
    }

}
