server:
  port: 8080

#TODO: figure out why I need this here and in bootstrap.yml
spring:
  application:
    name: testConsulAppClient

ribbon:
#  NIWSServerListClassName: org.springframework.cloud.consul.discovery.ConsulServerList
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true